# Generated by Django 2.1 on 2018-08-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumBoards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('min_read_level', models.PositiveSmallIntegerField()),
                ('min_write_level', models.PositiveSmallIntegerField()),
                ('sort_index', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'forum_boards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForumPostEdits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_time', models.DateTimeField()),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'forum_post_edits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForumPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('post_time', models.DateTimeField()),
                ('ip', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'forum_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForumSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('sort_index', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'forum_sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForumThreads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('post_time', models.DateTimeField()),
                ('views', models.PositiveIntegerField()),
                ('sticky', models.IntegerField()),
                ('closed', models.IntegerField()),
            ],
            options={
                'db_table': 'forum_threads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=256, null=True)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('filesize', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField()),
                ('title', models.CharField(max_length=128)),
                ('type', models.PositiveIntegerField()),
                ('rights', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OldUsers',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('salt', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'old_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('email_public', models.IntegerField()),
                ('website', models.CharField(max_length=128)),
                ('signature', models.TextField()),
                ('timezone', models.CharField(max_length=64)),
                ('timeformat', models.CharField(max_length=32)),
                ('staylogged', models.IntegerField()),
                ('location', models.CharField(max_length=128)),
                ('forumlimit_msg', models.PositiveIntegerField()),
                ('forumlimit_thr', models.PositiveIntegerField()),
                ('chat_color', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('alias', models.CharField(max_length=32)),
                ('level', models.PositiveIntegerField()),
                ('active', models.PositiveSmallIntegerField()),
                ('registered', models.DateTimeField()),
                ('lastcontact', models.DateTimeField()),
                ('lastlogoffpoint', models.DateTimeField()),
                ('spambot', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForumLastReads',
            fields=[
                ('tid', models.ForeignKey(db_column='tid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='olddata.ForumThreads')),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'forum_last_reads',
                'managed': False,
            },
        ),
    ]
