[tool.poetry]
name = "aetherguild.net"
version = "1.0.0"
package-mode = false
description = "Aether website"
authors = ["Tuomas Virtanen <katajakasa@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.13"
django = "^6.1.1"
django-imagekit = "^6.1.1"
django-crispy-forms = "^2.7"
django-silk = "^5.6.0"
django-timezone-field = "^7.2.2"
djangorestframework = "^3.18.1"
Pillow = "^12.3.0"
argon2-cffi = "^25.1.0"
django-precise-bbcode = "^1.2.16"
celery = {extras = ["redis"], version = "^5.6.3"}
requests = "^2.34.2"
uvicorn = "^0.54.0"
psycopg = {extras = ["binary", "pool"], version = "^3.3.6"}
crispy-bootstrap4 = "^2026.2"

[tool.poetry.group.dev.dependencies]
black = "^26.10.0"
isort = "^9.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.black]
line-length = 109
target-version = ['py313']
