[tool.poetry]
name = "aetherguild.net"
version = "1.0.0"
description = "Aether website"
authors = ["Tuomas Virtanen <katajakasa@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1"
django-imagekit = "^5.0.0"
django-redis = "^5.2.0"
django-crispy-forms = "^2.3"
django-silk = "^5.0.3"
django-timezone-field = "^7.0.0"
django-csp = "^3.7"
djangorestframework = "^3.14.0"
Pillow = "^9.4.0"
argon2-cffi = "^23.1.0"
django-precise-bbcode = "^1.2.15"
celery = "^5.2.7"
requests = "^2.28.2"
uvicorn = "^0.30.5"
psycopg = {extras = ["binary", "pool"], version = "^3.1.18"}
crispy-bootstrap4 = "^2024.1"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
isort = "^5.11.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.black]
line-length = 109
target-version = ['py311']
