# Generated by Django 2.1 on 2018-08-12 15:04

import django.db.models.deletion
import precise_bbcode.fields
from django.db import migrations, models

import aether.utils.misc


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("_description_rendered", models.TextField(blank=True, editable=False, null=True)),
                ("description", precise_bbcode.fields.BBCodeTextField(blank=True, no_rendered_field=True)),
                ("created_at", models.DateTimeField(db_index=True, default=aether.utils.misc.utc_now)),
            ],
            options={
                "verbose_name": "Gallery Group",
                "verbose_name_plural": "Gallery Groups",
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, default=aether.utils.misc.utc_now)),
                ("name", models.CharField(max_length=32)),
                ("original", models.ImageField(upload_to="gallery")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="gallery.GalleryGroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
    ]
