# Generated by Django 2.1 on 2018-08-05 21:10

import precise_bbcode.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nickname", models.CharField(max_length=128)),
                ("header", models.CharField(max_length=128)),
                ("_message_rendered", models.TextField(blank=True, editable=False, null=True)),
                ("message", precise_bbcode.fields.BBCodeTextField(no_rendered_field=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name="newsitem",
            index=models.Index(fields=["created_at", "deleted"], name="main_site_n_created_9dd415_idx"),
        ),
    ]
