# Generated by Django 2.1 on 2018-08-04 23:48

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='_message_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='message',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
    ]
