# Generated by Django 2.0.8 on 2018-08-07 23:16

from django.db import migrations, models

import aether.utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ("main_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="created_at",
            field=models.DateTimeField(default=aether.utils.misc.utc_now),
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="modified_at",
            field=models.DateTimeField(default=aether.utils.misc.utc_now),
        ),
    ]
