# Generated by Django 2.1 on 2018-08-03 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('sort_index', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ForumLastRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPostEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('sort_index', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('sticky', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.ForumBoard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=32)),
                ('signature', models.TextField(blank=True, default='')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Amsterdam')),
                ('message_limit', models.PositiveIntegerField()),
                ('thread_limit', models.PositiveIntegerField()),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='forumsection',
            index=models.Index(fields=['sort_index', 'deleted'], name='forum_forum_sort_in_f79027_idx'),
        ),
        migrations.AddField(
            model_name='forumpostedit',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.ForumPost'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.ForumThread'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumlastread',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.ForumThread'),
        ),
        migrations.AddField(
            model_name='forumlastread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumboard',
            name='read_perm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readable_boards', to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='forumboard',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.ForumSection'),
        ),
        migrations.AddField(
            model_name='forumboard',
            name='write_perm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writable_boards', to='auth.Permission'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['board', 'sticky', 'modified_at', 'deleted'], name='forum_forum_board_i_7f8da0_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpostedit',
            index=models.Index(fields=['post', 'created_at'], name='forum_forum_post_id_ca52d1_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['thread', 'created_at', 'deleted'], name='forum_forum_thread__4d1b9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumlastread',
            unique_together={('thread', 'user')},
        ),
        migrations.AddIndex(
            model_name='forumboard',
            index=models.Index(fields=['section', 'sort_index', 'deleted'], name='forum_forum_section_fb8305_idx'),
        ),
    ]
