# Generated by Django 2.1 on 2018-08-03 17:57

import aether.forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='forumpostedit',
            name='editor',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumlastread',
            name='created_at',
            field=models.DateTimeField(default=aether.forum.models.utc_now),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='created_at',
            field=models.DateTimeField(default=aether.forum.models.utc_now),
        ),
        migrations.AlterField(
            model_name='forumpostedit',
            name='created_at',
            field=models.DateTimeField(default=aether.forum.models.utc_now),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='created_at',
            field=models.DateTimeField(default=aether.forum.models.utc_now),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='modified_at',
            field=models.DateTimeField(default=aether.forum.models.utc_now),
        ),
    ]
