# Generated by Django 2.1 on 2018-08-04 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180803_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumboard',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='forum.ForumSection'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='message_limit',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='thread_limit',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
