# Generated by Django 2.0.8 on 2018-08-07 16:24

import aether.utils.misc
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumuser_last_all_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBCodeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(default=aether.utils.misc.utc_now)),
                ('original', models.ImageField(blank=True, upload_to='bbcode')),
            ],
        ),
    ]
