# Generated by Django 2.0.8 on 2018-08-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_bbcodeimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bbcodeimage",
            options={"verbose_name": "BBCode Image", "verbose_name_plural": "BBCode Images"},
        ),
        migrations.AlterField(
            model_name="bbcodeimage",
            name="original",
            field=models.ImageField(upload_to="bbcode"),
        ),
    ]
