# Generated by Django 2.0.8 on 2018-08-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_auto_20180808_0216"),
        ("forum", "0004_auto_20180807_2250"),
    ]

    operations = []
