# Generated by Django 2.1 on 2018-08-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20180805_0127'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='forumboard',
            index=models.Index(fields=['deleted'], name='forum_forum_deleted_e11d82_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['deleted'], name='forum_forum_deleted_7379a1_idx'),
        ),
        migrations.AddIndex(
            model_name='forumsection',
            index=models.Index(fields=['deleted'], name='forum_forum_deleted_f21cca_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['deleted'], name='forum_forum_deleted_91065e_idx'),
        ),
    ]
