# Generated by Django 2.1 on 2018-08-04 23:48

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20180805_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='_message_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='forumuser',
            name='_signature_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='message',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='signature',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, default='', no_rendered_field=True),
        ),
    ]
