# Generated by Django 5.1.6 on 2025-02-11 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0007_auto_20210616_2216"),
        ("gallery", "0002_auto_20210616_2216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumpost",
            name="attached_gallery",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_posts",
                to="gallery.gallerygroup",
            ),
        ),
    ]
